### PR TITLE
MWPW-128696 - Github actions for milo-fg AIO app

### PR DESCRIPTION
**Pull request by honstar**
- slightly adjusted OOTB config to use node 16
- removed auth sections, not needed for standalone apps to be deployed
- required github secrets already added to the milofg repository for both stage and prod namespaces
- add generic FG specific secrets as environment variables to deployment actions
- inject env vars for actions on package level

### CODE REVIEW

**Comment by sukamat** [comment]
@honstar Jens got the app based auth working as seen here: https://git.corp.adobe.com/jsingler/sp-auth#env
We are still working on integrating the app based auth into this milo-fg AIO app.

Could this github actions approach be used to inject some of the data stored in `.env` as listed in the [link above](https://git.corp.adobe.com/jsingler/sp-auth#env)?

cc: @raga-adbe-gh

**Review by sukamat — APPROVED** [review]

**Comment by sukamat** [comment]
@honstar Another question - How is the data set in the yaml file read? Is there OOTB API to read those new variables?

**Comment by sukamat** [comment]
> @honstar Another question - How is the data set in the yaml file read? Is there OOTB API to read those new variables?

Missed your other PR https://github.com/adobecom/milo-fg/pull/4. 
Looks like the data will be part of the params and can be accessed from there, correct?

**Comment by honstar** [comment]
> > @honstar Another question - How is the data set in the yaml file read? Is there OOTB API to read those new variables?
> 
> Missed your other PR #4. Looks like the data will be part of the params and can be accessed from there, correct?

Yes, all environment variables defined and injected via the `app.config.yaml` file using `inputs` are accessible directly from the object that is passed into your action's `main` method, e.g.:
```
function main(args) {
  const {
    fgSite,
    fgClientId,
    fgAuthority
  } = args;

  doSomething(fgSite);
}
```

**Comment by honstar** [comment]
> @honstar Jens got the app based auth working as seen here: https://git.corp.adobe.com/jsingler/sp-auth#env We are still working on integrating the app based auth into this milo-fg AIO app.
> 
> Could this github actions approach be used to inject some of the data stored in `.env` as listed in the [link above](https://git.corp.adobe.com/jsingler/sp-auth#env)?
> 
> cc: @raga-adbe-gh

Yes, this is essentially what the github actions do: environment variables defined like the floodgate ones [here](https://github.com/adobecom/milo-fg/pull/3/files#diff-9b0a49d1840887e3bd80347f2a20c2323881c4bcb9e7ccbccb40ebcbb54675c9R39) are persisted in an `.env` file before the app is deployed to I/O runtime.

The advantage is that we can store secrets in the `milo-fg` repo as secrets and reference these in the `deploy_stage` and `deploy_prod` gh-actions respectively. Please remember to inject these in the `app.config.yaml` file so that your actions have access to the additional env variables.

cc: @raga-adbe-gh

**Review by raga-adbe-gh — APPROVED** [review]

**Pull request merged**
